# Generated by Django 2.2 on 2021-05-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0004_auto_20210503_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
